package main

import (
	"context"
	"encoding/hex"
	"fmt"
	"math/big"
	"strings"
	"time"

	"github.com/iotexproject/go-pkgs/hash"
	"github.com/iotexproject/iotex-address/address"
	"github.com/iotexproject/iotex-analyser/db"
	"github.com/iotexproject/iotex-analyser/kernel"
	"github.com/iotexproject/iotex-analyser/models"
	"github.com/iotexproject/iotex-analyser/plugin"
	"github.com/iotexproject/iotex-core/v2/action"
	"github.com/iotexproject/iotex-core/v2/blockchain/block"
	slog "github.com/iotexproject/iotex-core/v2/pkg/log"
	"github.com/pkg/errors"
	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert/yaml"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

const VERSION = "1.0.0"

var (
	processTimeMetric = kernel.ProcessTimeMetric
)

type blockActionPartitionPlugin struct {
	batchSize     int
	partitionStep uint64
}

// Local model to target a different table name without changing global models
// Use models.BlockActionPartition to avoid inheriting indexes/tags from BlockAction

func (b blockActionPartitionPlugin) Name() string {
	return "block_action_partition"
}

func (b blockActionPartitionPlugin) Type() plugin.Type {
	return plugin.TypeStandard
}

func (b *blockActionPartitionPlugin) Start(ctx context.Context) error {
	// Read config
	b.partitionStep = 1000000
	if cfgData, ok := kernel.GetPluginConfigCtx(ctx); ok {
		cfg := &Config{}
		if err := yaml.Unmarshal(cfgData, cfg); err != nil {
			return errors.Wrapf(err, "failed to unmarshal plugin config: plugin %s, config %s", b.Name(), string(cfgData))
		} else {
			b.batchSize = cfg.BatchSize
			if cfg.PartitionStep > 0 {
				b.partitionStep = cfg.PartitionStep
			}
			slog.L().Info("read plugin config success", zap.String("plugin", b.Name()), zap.Any("config", cfg))
		}
	}

	// Create parent partitioned table if not exists
	if err := b.ensureParentPartitionedTable(); err != nil {
		return errors.Wrapf(err, "failed to start plugin %s", b.Name())
	}
	return nil
}

func (b *blockActionPartitionPlugin) ensureParentPartitionedTable() error {
	// Define columns aligned with models.BlockAction
	createParent := `
CREATE TABLE IF NOT EXISTS block_action_partition (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    action_hash VARCHAR(64) NOT NULL,
    action_type VARCHAR(32) NOT NULL,
	block_height BIGINT NOT NULL,
    sender VARCHAR(64) NOT NULL DEFAULT '',
    recipient VARCHAR(64) NOT NULL DEFAULT '',
    gas_price NUMERIC(42,0) NOT NULL DEFAULT 0,
	gas_limit INT4 NOT NULL DEFAULT 0,
    nonce BIGINT NOT NULL DEFAULT 0,
    amount NUMERIC(42,0) NOT NULL DEFAULT 0,
	gas_consumed INT4 NOT NULL DEFAULT 0,
    chain_id INT NOT NULL DEFAULT 0,
    encoding INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    contract_address VARCHAR(64) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 0,
    execution_revert_msg VARCHAR(255) NOT NULL DEFAULT '',
    payload BYTEA,
    timestamp TIMESTAMP,
    PRIMARY KEY (id, block_height)
) PARTITION BY RANGE (block_height);
`
	if err := db.DB().Exec(createParent).Error; err != nil {
		return err
	}
	// Basic useful indexes
	idxStmts := []string{
		`CREATE INDEX IF NOT EXISTS idx_bap_block_height ON block_action_partition (block_height)`,
		`CREATE INDEX IF NOT EXISTS idx_bap_action_hash ON block_action_partition (action_hash)`,
		`CREATE INDEX IF NOT EXISTS idx_bap_sender ON block_action_partition (sender)`,
		`CREATE INDEX IF NOT EXISTS idx_bap_recipient ON block_action_partition (recipient)`,
		`CREATE INDEX IF NOT EXISTS idx_bap_timestamp_date ON block_action_partition ((timestamp::date))`,
		`CREATE INDEX IF NOT EXISTS idx_bap_action_type ON block_action_partition (action_type);`,
		`CREATE INDEX IF NOT EXISTS idx_bap_contract_address ON block_action_partition(contract_address);`,
	}
	for _, stmt := range idxStmts {
		if err := db.DB().Exec(stmt).Error; err != nil {
			return err
		}
	}
	return nil
}

func (b blockActionPartitionPlugin) BatchSize() int {
	return b.batchSize
}

func getReceiptsFromBlock(blk *block.Block) map[hash.Hash256]*action.Receipt {
	receipts := make(map[hash.Hash256]*action.Receipt, len(blk.Receipts))
	for _, receipt := range blk.Receipts {
		receipts[receipt.ActionHash] = receipt
	}
	return receipts
}

func getPayloadAmount(act action.Action) (*big.Int, []byte) {
	amount := big.NewInt(0)
	var payload []byte
	switch a := act.(type) {
	case *action.Transfer:
		amount = a.Amount()
		payload = a.Payload()
	case *action.Execution:
		amount = a.Amount()
	case *action.DepositToRewardingFund:
		amount = a.Amount()
	case *action.ClaimFromRewardingFund:
		amount = a.ClaimAmount()
	case *action.CreateStake:
		amount = a.Amount()
		payload = a.Payload()
	case *action.DepositToStake:
		amount = a.Amount()
		payload = a.Payload()
	case *action.CandidateRegister:
		amount = a.Amount()
		payload = a.Payload()
	}
	return amount, payload
}

func getAccount(selp *action.SealedEnvelope, receipt *action.Receipt) (address.Address, string, error) {
	sender, err := address.FromBytes(selp.SrcPubkey().Hash())
	if err != nil {
		return nil, "", err
	}
	dst, _ := selp.Destination()
	return sender, dst, nil
}

func (b blockActionPartitionPlugin) PutBlocks(ctx context.Context, blks []*block.Block) error {
	var allActs []models.BlockActionPartition
	var from, to uint64
	for i, blk := range blks {
		acts, err := b.handleBlock(ctx, blk)
		if err != nil {
			return err
		}
		allActs = append(allActs, acts...)
		if i == 0 {
			from = blk.Height()
		}
		to = blk.Height()
	}
	return b.commitActs(allActs, from, to)
}

func (b blockActionPartitionPlugin) PutBlock(ctx context.Context, blk *block.Block) error {
	acts, err := b.handleBlock(ctx, blk)
	if err != nil {
		return err
	}
	return b.commitActs(acts, blk.Height(), blk.Height())
}

func (b blockActionPartitionPlugin) handleBlock(ctx context.Context, blk *block.Block) ([]models.BlockActionPartition, error) {
	t := time.Now()
	receipts := getReceiptsFromBlock(blk)
	processTimeMetric.WithLabelValues(b.Name(), "getReceipts").Observe(time.Since(t).Seconds())
	t = time.Now()
	var acts []models.BlockActionPartition

	for _, selp := range blk.Actions {
		actionHash, _ := selp.Hash()
		receipt, ok := receipts[actionHash]
		if !ok {
			continue
		}
		sender, dst, err := getAccount(selp, receipt)
		if err != nil {
			return nil, errors.Wrapf(err, "failed to get accounts from action %s", actionHash)
		}

		gasPrice := decimal.NewFromBigInt(selp.GasPrice(), 0)
		if selp.TxType() != action.LegacyTxType && selp.TxType() != action.AccessListTxType {
			gasPrice = decimal.NewFromBigInt(receipt.EffectiveGasPrice, 0)
		}
		gasLimit := selp.Gas()
		nonce := selp.Nonce()

		act := selp.Action()
		actionType := getActionTypeString(act)
		amount, payload := getPayloadAmount(act)

		amountDec := decimal.NewFromBigInt(amount, 0)
		acts = append(acts, models.BlockActionPartition{
			ActionHash:         hex.EncodeToString(actionHash[:]),
			ActionType:         actionType,
			BlockHeight:        blk.Height(),
			Sender:             sender.String(),
			Recipient:          dst,
			GasPrice:           gasPrice,
			GasLimit:           gasLimit,
			Nonce:              nonce,
			Amount:             amountDec,
			GasConsumed:        receipt.GasConsumed,
			ChainID:            selp.ChainID(),
			Encoding:           selp.Encoding(),
			Version:            0,
			ContractAddress:    receipt.ContractAddress,
			Status:             receipt.Status,
			Timestamp:          time.Unix(blk.Timestamp().Unix(), 0),
			ExecutionRevertMsg: strings.ReplaceAll(receipt.ExecutionRevertMsg(), string([]byte{0x00}), "0x00"),
			Payload:            payload,
		})
	}
	processTimeMetric.WithLabelValues(b.Name(), "makeData").Observe(time.Since(t).Seconds())
	return acts, nil
}

func (b blockActionPartitionPlugin) ensurePartitions(from, to uint64) error {
	step := b.partitionStep
	if step == 0 {
		step = 1000000
	}
	start := (from / step) * step
	end := ((to / step) + 1) * step
	for p := start; p < end; p += step {
		name := fmt.Sprintf("block_action_partition_p_%d", p)
		stmt := fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s PARTITION OF block_action_partition FOR VALUES FROM (%d) TO (%d)", name, p, p+step)
		if err := db.DB().Exec(stmt).Error; err != nil {
			return err
		}
	}
	return nil
}

func (b blockActionPartitionPlugin) commitActs(acts []models.BlockActionPartition, from, to uint64) error {
	// Transaction 1: Ensure partitions exist (separate transaction, DDL with implicit commit)
	if err := b.ensurePartitions(from, to); err != nil {
		return errors.Wrap(err, "failed to ensure partitions")
	}

	// Transaction 2: Insert data
	t := time.Now()
	err := db.DB().Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("block_height >= ? AND block_height <= ?", from, to).Delete(&models.BlockActionPartition{}).Error; err != nil {
			return err
		}
		processTimeMetric.WithLabelValues(b.Name(), "deleteIfExisted").Observe(time.Since(t).Seconds())
		t = time.Now()
		if err := tx.Model(&models.BlockActionPartition{}).CreateInBatches(acts, 200).Error; err != nil {
			return err
		}
		processTimeMetric.WithLabelValues(b.Name(), "insertData").Observe(time.Since(t).Seconds())
		t = time.Now()
		e := db.UpdateIndexHeightByTx(tx, b.Name(), to)
		processTimeMetric.WithLabelValues(b.Name(), "updateIndex").Observe(time.Since(t).Seconds())
		return e
	})
	return err
}

func (b blockActionPartitionPlugin) Stop(ctx context.Context) error { return nil }

func (b blockActionPartitionPlugin) CatchUpSafe() bool { return true }

func (b blockActionPartitionPlugin) Version() string { return VERSION }

// exported
var Plugin = blockActionPartitionPlugin{}
