server:
#  http: 127.0.0.1:8989
  plugins:
    - block.so
    - blockmeta.so
    - blockaction.so
database:
  dsn: root:root@tcp(127.0.0.1:3306)/iotex-analyser
iotex:
  chainEndPoint: api.testnet.iotex.one:80
  batchSize: 128
  pluginReportInterval: 50s
blockDB:
  dbPath: /media/millken/SAMSUNG/iotex-var/data/chain.db
log:
  zap:
    development: false
    level: debug
    encoding: console
    disableCaller: false
    disableStacktrace: false
    outputPaths: ["stderr"]
    errorOutputPaths: ["stderr"]
  stdLogRedirect: true  
subLogs:
  pluginRunner:
    zap:
      development: false
      level: info
      encoding: console
      disableCaller: false
      disableStacktrace: false
      outputPaths: ["stderr"]
      errorOutputPaths: ["stderr"]
    stdLogRedirect: true  