server:
#  http: 127.0.0.1:8989
  plugins:
    # - block.so
    # - blockmeta.so
    # - blockmeta_reward.so
    # - blockaction.so
    - delegates.so
database:
  dsn: root:root@tcp(127.0.0.1:3306)/iotex-analyser
iotex:
  catchUpMode: true
  chainEndPoint: api.mainnet.iotex.one:80
  batchSize: 128
blockDB:
  dbPath: chainlive-mainnet.db
log:
  zap:
    development: false
    level: debug
    encoding: console
    disableCaller: false
    disableStacktrace: false
    outputPaths: ["stderr"]
    errorOutputPaths: ["stderr"]
  stdLogRedirect: true  
subLogs:
  pluginRunner:
    zap:
      development: false
      level: info
      encoding: console
      disableCaller: false
      disableStacktrace: false
      outputPaths: ["stderr"]
      errorOutputPaths: ["stderr"]
    stdLogRedirect: true  