server:
  #plugin metrics
  # http: 127.0.0.1:8989
  #debug port
  # httpAdminPort: 8988
  #loaded default plugin list
  plugins:
    - account_meta.so
    - account_vote.so
    - action.so
    - action_execution.so
    # - airdrip.so
    - block.so
    - block_action.so
    - block_meta.so
    - block_receipt.so
    - block_reward.so
    - candidate.so
    - delegate.so
    - delegates_worker.so
    - hermes.so
    - iotexprice_worker.so
    - probation.so
    # - staking_action.so
    - staking_actions.so
    - staking_bucket.so
    - token_erc20.so
    - token_erc721.so
database:
  driver: postgres
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  name: iotexmainnet
iotex:
  #catchUpMode: true
  chainEndPoint: api.iotex.one:80
  DisableRebuildDB: true
blockDB:
  dbPath: db/chain.db
log:
  zap:
    level: info
    encoding: console
    disableCaller: false
    disableStacktrace: false
    outputPaths: ["stderr"]
    errorOutputPaths: ["stderr"]
  stdLogRedirect: false 
  #stderrRedirectFile: std.log
genesis:
  account:
    initBalances:
      io10t7juxazfteqzjsd6qjk7tkgmngj2tm7n4fvrd: "1000000000000000000000000000"
      io120au9ra0nffdle04jx2g5gccn6gq8qd4fy03l4: "7000000000000000000000000000"
      io1yrzvkucxpytn4fru35lc8r8jk4jtue4syg8d4h: "800000000000000000000000000"