syntax = "proto3";

package api;
import "google/api/annotations.proto";

option go_package = "./api";

message AccountRequest {
  repeated BalanceRquest request = 1;
}

message BalanceRquest {
  string address = 1;
  uint64 height = 2;
  string contract_address = 3;
}

message BalanceResponse {
  string address = 1;
  uint64 height = 2;
  string contract_address = 3;
  string balance  = 4;
}

message AccountResponse { 
  repeated BalanceResponse response = 1;
}

message AccountErc20TokenRequest {
  repeated BalanceRquest request = 1;
}

service AccountService {
  rpc GetIotexBalanceByHeight(AccountRequest) returns (AccountResponse) {
    option (google.api.http) = {
      post: "/api.AccountService.GetIotexBalanceByHeight"
      body: "*"
    };
  };
  rpc GetErc20TokenBalanceByHeight(AccountErc20TokenRequest) returns (AccountResponse) {
    option (google.api.http) = {
      post: "/api.AccountService.GetErc20TokenBalanceByHeight"
      body: "*"
    };
  };

}