syntax = "proto3";

package api;
import "google/api/annotations.proto";

option go_package = "./api";

message AccountRequest {
  string address = 1;
  uint64 height = 2;
}

message AccountResponse { 
  uint64 nonce  = 1;
  string balance  = 2;
}

service AccountService {
  rpc GetIotexBalanceByHeight(AccountRequest) returns (AccountResponse) {
    option (google.api.http) = {
      post: "/api.AccountService.GetIotexBalanceByHeight"
      body: "*"
    };
  };
  rpc GetErc20TokenBalanceByHeight(AccountRequest) returns (AccountResponse) {
    option (google.api.http) = {
      post: "/api.AccountService.GetErc20TokenBalanceByHeight"
      body: "*"
    };
  };

}